### ISSUE TITLE
Add module for static routes on Ms350 switches

### ISSUE THREAD

**Issue by pokepoke81** [CiscoDevNet/ansible-meraki#116]
Please add a module for managing static routes on MS350 switches.

**Comment by kbreit** [comment]
@pokepoke81 i hope you’re well. Do you know if this API endpoint exists? I haven’t seen it in the documentation.

**Comment by kbreit** [comment]
Good and bad news. Good news is I do see there is an endpoint for configuring static routes on MS switches. The bad news is it’s in V1 of the API and not V0. V1 will be a breaking change and will likely be version 2.0 of my collection. I’m going to start on migrating to the V1 API before too long but it’s not something that I can easily code now. I am adding this to a new 2.0 milestone. My goal will be to have this module created for 2.0 of the collection.

**Comment by pokepoke81** [comment]
Thanks @kbreit. I saw the Cisco Live talk on the v1 API and wondered what that looked like for migrating too.

**Comment by kbreit** [comment]
@pokepoke81 I created a branch at https://github.com/CiscoDevNet/ansible-meraki/tree/release-branch/2.0 where you can try the Ansible support for the v1 API. I should note though, it's VERY much in development and I've only tested `meraki_organization` and `meraki_network`. If you run this, make sure you do it in a non-production organization and expect bugs. But...if you get bugs, please let me know.

**Comment by kbreit** [comment]
@pokepoke81 I started working on this tonight and realized I need to do the routed interface module first. I'll be working on both of these.

**Comment by kbreit** [comment]
...and that one requires OSPF settings.

**Comment by richardjohnallsopp** [comment]
Can I get access to this? Happy to test it out for you if needed?

**Comment by kbreit** [comment]
@richardjohnallsopp Take a look at my fork. It's in the ms_350_static branch or something like that. Let me know if you need help getting it setup.

**Comment by kbreit** [comment]
@richardjohnallsopp I should note, the module (https://github.com/kbreit/ansible-meraki/blob/2.0/ms_350_static/plugins/modules/meraki_ms_static_route.py) sometimes has some dependencies on other configurations within Meraki. I've been having problems with one of those dependencies which is why this module isn't released since I can't do the entire thing as code.
