### ISSUE TITLE
Rename modules to include product line

### ISSUE THREAD

**Issue by pokepoke81** [CiscoDevNet/ansible-meraki#158]
Consider renaming the modules to include the targeted hardware in the title. 

meraki_admin.py => meraki_org_admin.py
meraki_config_template.py => meraki_org_config_template.py
meraki_content_filtering.py => meraki_mx_content_filtering.py
meraki_device.py => meraki_network_device.py
meraki_firewalled_services.py => meraki_network_firewalled_services.py
meraki_intrusion_prevention.py => meraki_mx_intrusion_prevention.py
meraki_malware.py =>meraki_network_malware.py
meraki_management_interface.py = meraki_network_management_interface.py
meraki_mr_l3_firewall.py => same
meraki_ms_link_aggregation.py => same
meraki_mx_l3_firewall.py => same
meraki_mx_l7_firewall.py => same
meraki_mx_site_to_site_firewall.py => same
meraki_mx_uplink.py => same
meraki_nat.py => meraki_mx_nat.py
meraki_network.py => same
meraki_organization.py => same
meraki_site_to_site_vpn.py => meraki_network_site_to_site.vpn.py
meraki_snmp.py => meraki_network_snmp.py
meraki_ssid.py => meraki_mr_ssid.py
meraki_static_route.py => meraki_mx_static_route.py 
meraki_switch_access_list.py => meraki_ms_access_list.py
meraki_switch_stack.py => meraki_ms_stack.py
meraki_switch_storm_control.py => meraki_ms_storm.control.py
meraki_switchport.py => meraki_ms_switchport.py
meraki_syslog.py = meraki_network_syslog.py
meraki_vlan.py = meraki_mx_vlan.py
meraki_webhook.py = meraki_network_webhook.py

**Comment by kbreit** [comment]
This will be a checklist monitoring the status of each one. A check doesn't necessarily mean it will be renamed but it does indicate there is resolution.

- [ ] meraki_admin.py => meraki_org_admin.py
- [ ] meraki_config_template.py => meraki_org_config_template.py
- [ ] meraki_content_filtering.py => meraki_mx_content_filtering.py
- [ ] meraki_device.py => meraki_network_device.py
- [ ] meraki_firewalled_services.py => meraki_network_firewalled_services.py
- [ ] meraki_intrusion_prevention.py => meraki_mx_intrusion_prevention.py
- [ ] meraki_malware.py =>meraki_network_malware.py
- [ ] meraki_management_interface.py = meraki_network_management_interface.py
- [ ] meraki_mr_l3_firewall.py => same
- [ ] meraki_ms_link_aggregation.py => same
- [ ] meraki_mx_l3_firewall.py => same
- [ ] meraki_mx_l7_firewall.py => same
- [ ] meraki_mx_site_to_site_firewall.py => same
- [ ] meraki_mx_uplink.py => same
- [ ] meraki_nat.py => meraki_mx_nat.py
- [ ] meraki_network.py => same
- [ ] meraki_organization.py => same
- [ ] meraki_site_to_site_vpn.py => meraki_network_site_to_site.vpn.py
- [ ] meraki_snmp.py => meraki_network_snmp.py
- [ ] meraki_ssid.py => meraki_mr_ssid.py
- [ ] meraki_static_route.py => meraki_mx_static_route.py
- [ ] meraki_switch_access_list.py => meraki_ms_access_list.py
- [ ] meraki_switch_stack.py => meraki_ms_stack.py
- [ ] meraki_switch_storm_control.py => meraki_ms_storm.control.py
- [ ] meraki_switchport.py => meraki_ms_switchport.py
- [ ] meraki_syslog.py = meraki_network_syslog.py
- [ ] meraki_vlan.py = meraki_mx_vlan.py
- [ ] meraki_webhook.py = meraki_network_webhook.py

**Comment by kbreit** [comment]
I am closing this as resolved. Not all modules were renamed. But those specific to a product were. Thank you for the suggestion!
