### ISSUE TITLE
pushed test coverage data/reports nto pypi

### ISSUE THREAD

**Issue by gosunilgo** [CiscoDevNet/ansible-meraki#211]
Someone pushed test coverage reports/data into pypi.  500 MB of wasted space.

**Comment by gundalow** [comment]
@gosunilgo Thank you for reporting this, this has been fixed in the latest release of cisco.meraki, we've also made a release of `ansible==2.10.2` https://groups.google.com/g/ansible-devel/c/CcB43Ale5HY the only difference from `ansible==2.10.2` is the smaller download & install size.

**Comment by gosunilgo** [comment]
:+1:
