### ISSUE TITLE
meraki_site_to_site_vpn module not found

### ISSUE THREAD

**Issue by larsrei** [CiscoDevNet/ansible-meraki#221]
Hello,

I install ansible-meraki but the module "meraki_site_to_site_vpn" is not found. Other modules like "meraki_network" I can use without problems.
I use version 2.2.0 and ansible version 2.10.5

Code:
`---
- name: Query network vpn-hub Id from our organization
  meraki_network:
    state: query
    auth_key: "{{ auth_key }}"
    org_name: "{{ org_name }}"
    net_name: "{{ vpn_hub }}"
  delegate_to: localhost
  register: vpn_hub

- name: Set spoke mode and vpn
  meraki_site_to_site_vpn:
    state: present
    auth_key: "{{ auth_key }}"
    org_name: "{{ org_name }}"
    net_name: "{{ net_name }}"
    mode: spoke
    subnets:
      - local_subnet: "{{ subnet_10 }}"
        use_vpn: true
    hubs:
      - hub_id: "{{ vpn_hub.data.id }}"
        use_default_route: true
  delegate_to: localhost
...`

`ansible-playbook 2.10.5
  config file = /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/ansible.cfg
  configured module search path = ['/home/fa9/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fa9/Development/venv-auto-train/lib/python3.8/site-packages/ansible
  executable location = /home/fa9/Development/venv-auto-train/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Using /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/inventory.yml as it did not pass its verify_file() method
Parsed /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/inventory.yml inventory source with yaml plugin
redirecting (type: modules) ansible.builtin.meraki_network to cisco.meraki.meraki_network
Loading collection cisco.meraki from /home/fa9/.ansible/collections/ansible_collections/cisco/meraki
redirecting (type: modules) ansible.builtin.meraki_device to cisco.meraki.meraki_device
redirecting (type: modules) ansible.builtin.meraki_vlan to cisco.meraki.meraki_vlan
redirecting (type: modules) ansible.builtin.meraki_snmp to cisco.meraki.meraki_snmp
redirecting (type: modules) ansible.builtin.meraki_syslog to cisco.meraki.meraki_syslog
redirecting (type: modules) ansible.builtin.meraki_network to cisco.meraki.meraki_network
ERROR! couldn't resolve module/action 'meraki_site_to_site_vpn'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/roles/manage-vpn/tasks/main.yml': line 12, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Set spoke mode and vpn
  ^ here
`

When I delete the "Set spoke mode and vpn" it runs.

`TASK [manage-vpn : Query network vpn-hub Id from our organization] ********************************************************************************************************************************************
task path: /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/roles/manage-vpn/tasks/main.yml:2
ok: [DE_TRAIN_8599] => {
    "changed": false,
    "data": {
        "enrollment_string": null,
        "id": "N_111111111111",
        "name": "TPL-TEST",
        "notes": "",
        "organization_id": "22222222",
        "product_types": [
            "appliance"
        ],
        "tags": [
            "TAG-DE-TRAIN"
        ],
        "time_zone": "Europe/Berlin",
        "url": "https://n199.meraki.com/TPL-TE/n/qtWd0dhd/manage/usage/list"
    },
    "invocation": {
        "module_args": {
            "auth_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "enable_vlans": null,
            "follow_redirects": "all",
            "host": "api.meraki.com",
            "internal_error_retry_time": 60,
            "local_status_page_enabled": null,
            "net_id": null,
            "net_name": "TPL-TEST",
            "org_id": null,
            "org_name": "TP Name Test",
            "output_format": "snakecase",
            "output_level": "normal",
            "protocol": "https",
            "rate_limit_retry_time": 165,
            "remote_status_page_enabled": null,
            "state": "query",
            "tags": null,
            "timeout": 30,
            "timezone": null,
            "type": null,
            "use_https": true,
            "use_proxy": false,
            "validate_certs": true
        }
    },
    "response": "OK (unknown bytes)",
    "status": 200
}

`

Have some idea?

best regards,
Lars

**Comment by kbreit** [comment]
This module went through a rename so I need to look into why it's not working. However, please try `meraki_mx_site_to_site_vpn`. Notice it specifies `mx` in the name. Let me know if that works.

**Comment by larsrei** [comment]
Hi,

I try it but same result:
`ansible-playbook 2.10.5
  config file = /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/ansible.cfg
  configured module search path = ['/home/fa9/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fa9/Development/venv-auto-train/lib/python3.8/site-packages/ansible
  executable location = /home/fa9/Development/venv-auto-train/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Using /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/inventory.yml as it did not pass its verify_file() method
Parsed /home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/inventory.yml inventory source with yaml plugin
redirecting (type: modules) ansible.builtin.meraki_network to cisco.meraki.meraki_network
Loading collection cisco.meraki from /home/fa9/.ansible/collections/ansible_collections/cisco/meraki
redirecting (type: modules) ansible.builtin.meraki_device to cisco.meraki.meraki_device
redirecting (type: modules) ansible.builtin.meraki_vlan to cisco.meraki.meraki_vlan
redirecting (type: modules) ansible.builtin.meraki_snmp to cisco.meraki.meraki_snmp
redirecting (type: modules) ansible.builtin.meraki_syslog to cisco.meraki.meraki_syslog
redirecting (type: modules) ansible.builtin.meraki_network to cisco.meraki.meraki_network
ERROR! couldn't resolve module/action 'meraki_mx_site_to_site_vpn'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/fa9/Development/venv-auto-train/automation-trainroom/ansible-data/roles/manage-vpn/tasks/main.yml': line 12, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Set spoke mode and vpn
  ^ here
`

**Comment by kbreit** [comment]
For the module, refer to it explicitly as a collection. Use `cisco.meraki.meraki_mx_site_to_site_vpn` or whatever module you want to use. Give that a try, did it fix it?

**Comment by larsrei** [comment]
Ok this is working. Than I can use the module and site-2-site vpn is configured correct.
Bug or Feature ? ;)

**Comment by kbreit** [comment]
It's a bug in that my documentation should explain it better. For Ansible? Either way. It was finding the built in modules before it looked for the collection which is why it failed. By prefixing it with `Cisco.Meraki` it was explicit and went to the collection.

**Comment by larsrei** [comment]
Ok I understand. Than I will go forward on my side and know what I can try on such a error. Many thanks for helping with this problem!!
