### ISSUE TITLE
Error Content Filter MX if setting is present

### ISSUE THREAD

**Issue by larsrei** [CiscoDevNet/ansible-meraki#222]
Hi,

I use the follow config für content filter on mx firewall.
```
- name: Set blocked URL category Content Filter
  meraki_content_filtering:
    state: present
    auth_key: "{{ auth_key }}"
    org_name: "{{ org_name }}"
    net_name: "{{ net_name }}"
    category_list_size: full list
    blocked_categories:
      - "Abused Drugs"
      - "Adult and Pornography"
      - "Alcohol and Tobacco"
      - "Bot Nets"
      - "Confirmed SPAM Sources"
      - "Gambling"
      - "Hacking"
      - "Hate and Racism"
      - "Illegal"
      - "Malware Sites"
      - "Open HTTP Proxies"
      - "Peer to Peer"
      - "Phishing and Other Frauds"
      - "Proxy Avoidance and Anonymizers"
```
On first run it works and the content filter will configured correct. All is set right. If I start playbook again I see follow error:

Log:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/fa9/.ansible/tmp/ansible-tmp-1612801477.1214135-39922-28099220429329/AnsiballZ_meraki_content_filtering.py", line 102, in <module>
    _ansiballz_main()
  File "/home/fa9/.ansible/tmp/ansible-tmp-1612801477.1214135-39922-28099220429329/AnsiballZ_meraki_content_filtering.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/fa9/.ansible/tmp/ansible-tmp-1612801477.1214135-39922-28099220429329/AnsiballZ_meraki_content_filtering.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_content_filtering', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_meraki_content_filtering_payload_nj2izgda/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py", line 282, in <module>
  File "/tmp/ansible_meraki_content_filtering_payload_nj2izgda/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py", line 267, in main
  File "/tmp/ansible_meraki_content_filtering_payload_nj2izgda/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py", line 203, in generate_diff
TypeError: 'NoneType' object is not subscriptable
fatal: [DE_TRAIN_8599]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1612801477.1214135-39922-28099220429329/AnsiballZ_meraki_content_filtering.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1612801477.1214135-39922-28099220429329/AnsiballZ_meraki_content_filtering.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1612801477.1214135-39922-28099220429329/AnsiballZ_meraki_content_filtering.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_content_filtering', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_content_filtering_payload_nj2izgda/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py\", line 282, in <module>\n  File \"/tmp/ansible_meraki_content_filtering_payload_nj2izgda/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py\", line 267, in main\n  File \"/tmp/ansible_meraki_content_filtering_payload_nj2izgda/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py\", line 203, in generate_diff\nTypeError: 'NoneType' object is not subscriptable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

When I go and change something on the content filter on meraki site (for example delete a category), so that config is different to ansible config than it work one time again.
So seems that there is a problem if config ansible present on meraki dashboard.

best regards,
Lars

**Comment by larsrei** [comment]
Error for me is in this function, object before or after are not correct
`    def generate_diff(self, before, after):
        """Creates a diff based on two objects. Applies to the object and returns nothing.
        """
        try:
            diff = recursive_diff(before, after)
            **self.result['diff'] = {'before': diff[0],
                                   'after': diff[1]}**
        except AttributeError:  # Normally for passing a list instead of a dict
            diff = recursive_diff({'data': before},
                                  {'data': after})
            self.result['diff'] = {'before': diff[0]['data'],
                                   'after': diff[1]['data`

**Comment by kbreit** [comment]
Thank you for reporting this bug. I should have some time today to look into this and will let you know what I find.

**Comment by kbreit** [comment]
@larsrei Please try the fix in PR #224 and let me know if it works.

**Comment by larsrei** [comment]
I change this in my venv in the ansible-collection/cisco/meraki/plugins/modules/meraki_mx_content_filtering.py but become error.

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [DE_TRAIN_8599]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1613466232.6019855-11593-222403368653490/AnsiballZ_meraki_content_filtering.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1613466232.6019855-11593-222403368653490/AnsiballZ_meraki_content_filtering.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1613466232.6019855-11593-222403368653490/AnsiballZ_meraki_content_filtering.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_content_filtering', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_content_filtering_payload_bee2678k/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py\", line 282, in <module>\n  File \"/tmp/ansible_meraki_content_filtering_payload_bee2678k/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py\", line 267, in main\n  File \"/tmp/ansible_meraki_content_filtering_payload_bee2678k/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py\", line 203, in generate_diff\nTypeError: 'NoneType' object is not subscriptable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`
Must I change more ?

**Comment by kbreit** [comment]
Can you confirm you have the latest file? My current one has 291 or 292 lines in it. My integration tests work and your traceback is pointing to your using check mode, which I don't think you mentioned.

**Comment by kbreit** [comment]
If you're indeed using the latest version would you please also give a detailed explanation of your before and after state when this happens? For example, do you have a different policy in place, that is overwritten, then you issue it again and there's no change and there's a crash? My code is working in my integration tests and I feel there's a corner case your situation has which is causing this bug which I am not capturing.

**Comment by larsrei** [comment]
OK, I try some tests but before one question. I change the code in file meraki_mx_content_filtering.py but what is with meraki_content_filtering.py? I change it here too but no effekt.
Tests:
- Create new content filtering work
- Change content filtering work (add category on ansible side to update passed and delete a category on meraki side work too)
- Same content on ansible side and meraki side work not

Example: Delete a category on meraki site and let run it 2 times.
`...
TASK [manage-firewall : Set blocked URL category Content Filter] **********************************************************************************************************************************************
changed: [DE_TRAIN_8599]

PLAY RECAP ****************************************************************************************************************************************************************************************************
DE_TRAIN_8599              : ok=9    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Second time:
...
TASK [manage-firewall : Set blocked URL category Content Filter] **********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [DE_TRAIN_8599]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1613552048.3382304-13824-122131472363726/AnsiballZ_meraki_content_filtering.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1613552048.3382304-13824-122131472363726/AnsiballZ_meraki_content_filtering.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/fa9/.ansible/tmp/ansible-tmp-1613552048.3382304-13824-122131472363726/AnsiballZ_meraki_content_filtering.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_content_filtering', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_content_filtering_payload_4m52bs3b/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py\", line 282, in <module>\n  File \"/tmp/ansible_meraki_content_filtering_payload_4m52bs3b/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_content_filtering.py\", line 267, in main\n  File \"/tmp/ansible_meraki_content_filtering_payload_4m52bs3b/ansible_meraki_content_filtering_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py\", line 203, in generate_diff\nTypeError: 'NoneType' object is not subscriptable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ****************************************************************************************************************************************************************************************************
DE_TRAIN_8599              : ok=8    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

`
What is defined:
`- name: Set blocked URL category Content Filter
  tags: config
  meraki_content_filtering:
    state: present
    auth_key: "{{ auth_key }}"
    org_name: "{{ org_name }}"
    net_name: "{{ net_name }}"
    category_list_size: full list
    blocked_categories:
      - "Abused Drugs"
      - "Adult and Pornography"
      - "Alcohol and Tobacco"
      - "Bot Nets"
      - "Confirmed SPAM Sources"
      - "Gambling"
      - "Hacking"
      - "Hate and Racism"
      - "Illegal"
      - "Malware Sites"
      - "Open HTTP Proxies"
      - "Peer to Peer"
      - "Phishing and Other Frauds"
      - "Proxy Avoidance and Anonymizers"`

![Bildschirmfoto von 2021-02-17 10-08-10](https://user-images.githubusercontent.com/24608756/108181368-1e7b3480-7108-11eb-8432-c0f9b93acd74.png)

**Comment by larsrei** [comment]
@kbreit question: I install it over ansible-collection and change the files in my venv path. Is this enough or can I do it a better way?

**Comment by kbreit** [comment]
You should be able to just replace the collection file. In my situation that's located at `~/.ansible/collections` I think.

**Comment by larsrei** [comment]
@kbreit ok the patch is working. I can do now anything as you describe.

I had 2 installation of ansible-meraki. One in my venv and one in my home (~/.ansible/collections). The venv was using the collection in my home and so the changes was not working.

For all this patch works fine.

**Comment by kbreit** [comment]
Very cool. I will merge this PR and do a new release today or tomorrow. Thank you for your report and assistance verifying.
