### ISSUE TITLE
meraki_switchport access_policy_types choices don't match.

### ISSUE THREAD

**Issue by jeffkala** [CiscoDevNet/ansible-meraki#227]
The Ansible Module has choices:
    access_policy_type:
        choices: [Open, Custom access policy, MAC whitelist, Sticky MAC whitelist].
        
 When a playbook uses this keyword, it will fail.
 
     "msg": "HTTP error 400 - https://api.meraki.com/api/v1/devices/Q2HP-HMV3-8PZW/switch/ports/6 - 'accessPolicyType' must be one of: 'Open', 'Custom access policy', 'MAC allow list' or 'Sticky MAC allow list'",
    "response": "OK (unknown bytes)",
    "status": 400

Looking at API docs, the valid options are listed in the schema.
https://developer.cisco.com/meraki/api-v1/#!update-device-switch-port

accessPolicyType:
string
The type of the access policy of the switch port. Only applicable to access ports. Can be one of 'Open', 'Custom access policy', 'MAC allow list' or 'Sticky MAC allow list'.

Fix is to change the `choices` in the arg_spec to the accurate options, which are 'Open', 'Custom access policy', 'MAC allow list' or 'Sticky MAC allow list'.

**Comment by jeffkala** [comment]
This can be assigned to me.  Will be updating this along with adding additional functionality to this module.

**Comment by kbreit** [comment]
Thank you for the report. I set you as assigned.
