### ISSUE TITLE
L3 interfaces and stacks

### ISSUE THREAD

**Issue by jshively37** [CiscoDevNet/ansible-meraki#251]
Would it be possible to pass stack id to the L3 interfaces module?

This would be great for those who use stacks instead of single switches for configuring L3 interfaces.

**Comment by kbreit** [comment]
Great idea. Let me look into the capabilities within the API and see if it's possible. If it is, I'll add support.

**Comment by kbreit** [comment]
@jshively37 - There is a layer 3 interface endpoint for stacks. I'm going to create a new module to support this endpoint. While I'm at it, there are endpoints for static routes and DHCP on stacks which I may implement too.

**Comment by kbreit** [comment]
I have it mostly written. Documentation needs to be updated but I should have a new version released with this module.

**Comment by kbreit** [comment]
@jshively37 Would you be able to test the new module? I need to add another couple integration tests but most of them are in place. If so, please use the code in #252 and let me know how it goes.

**Comment by jshively37** [comment]
Definitely will this weekend on the lab devices.

**Comment by jshively37** [comment]
also appreciate all the hard work!

**Comment by kbreit** [comment]
Integration tests are upgraded. Let me know how your testing goes.
