### ISSUE TITLE
Api key not working from an environment variable

### ISSUE THREAD

**Issue by mtb-xt** [CiscoDevNet/ansible-meraki#254]
Hello.

I'm trying to use meraki modules with my api key in the environment variable, but it doesn't work:

```
[hawara@phoenix infra-ansible]$ echo $MERAKI_KEY 
*REDACTED*
[hawara@phoenix infra-ansible]$ env | grep MERAKI_KEY
MERAKI_KEY=*REDACTED*

[hawara@phoenix infra-ansible]$ ansible-playbook -vvvv meraki.yml

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_key": null,
            "host": "api.meraki.com",
            "internal_error_retry_time": 60,
            "net_id": null,
            "net_name": "*REDACTED*",
            "org_id": null,
            "org_name": "*REDACTED*",
            "output_format": "snakecase",
            "output_level": "normal",
            "rate_limit_retry_time": 165,
            "rules": null,
            "state": "query",
            "syslog_default_rule": null,
            "timeout": 30,
            "use_https": true,
            "use_proxy": false,
            "validate_certs": true
        }
    },
    "msg": "missing required arguments: auth_key"
}
```

The playbook contents is simple copy from the examples:
```
- hosts: 127.0.0.1
  vars:
    - front_rules: []
    - back_rules: []
  tasks:
    - name: Get firewall rules
      meraki_mx_l3_firewall:
        org_name: *REDACTED*
        net_name: *REDACTED*     
        state: query
      register: rules
    - set_fact:
        original_ruleset: '{{rules.data}}'
    - debug:
        var: 'original_ruleset'
```

```
ansible-playbook [core 2.11.4] 
  config file = /home/hawara/*REDACTED*/infra-ansible/ansible.cfg
  configured module search path = ['/home/hawara/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/hawara/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

**Comment by kbreit** [comment]
Thank you for the big report. Has it worked in the past?

**Comment by mtb-xt** [comment]
> Thank you for the big report. Has it worked in the past?

It's the first time I'm trying the modules...

**Comment by kbreit** [comment]
Okay thank you for the report. I'm going to look into it over the next few days. There are some recent pull requests I merged so I'll wait until I resolve this and do a new release with this bugfix when I find.

**Comment by kbreit** [comment]
When you executed the playbook you passed in `-vvvv`. Can you paste in the full sanitized output from that verbosity output? Also, one change that I don't think will fix it. Instead of setting a host of localhost, set the `connection` to `local`.

**Comment by mtb-xt** [comment]
> When you executed the playbook you passed in `-vvvv`. Can you paste in the full sanitized output from that verbosity output? Also, one change that I don't think will fix it. Instead of setting a host of localhost, set the `connection` to `local`.

Thank you for your help! My results:
Tried with 
```
- hosts: localhost
  connection: local
``` 
instead of `hosts: 127.0.01` - no changes, still fails.

Full sanitized output here:
https://gist.github.com/mtb-xt/9c9997ec6e2fc453c228c40ce01ed519

Just to make sure it works, I specified the `auth_key` option, and then it works, of course.

**Comment by kbreit** [comment]
Taking a stab here. I haven't been able to reproduce your bug yet. I am using a different module (`meraki_organization`) but that shouldn't matter. One difference I see is the line bolded in your output:

```
PLAYBOOK: meraki.yml *************************************************************************************************************************
Positional arguments: meraki.yml
verbosity: 4
remote_user: ansible
connection: smart
timeout: 30
**become: True**
become_method: sudo
tags: ('all',)
inventory: ('/home/hawara/*work*/infra-ansible/inventories',)
forks: 100
1 plays in meraki.yml
```

My output doesn't have that line. If it's doing privilege escalation, that may be dropping the environment variable. Is there something in your system or `ansible.cfg` which is setting `become`?

**Comment by mtb-xt** [comment]
> Taking a stab here. I haven't been able to reproduce your bug yet. I am using a different module (`meraki_organization`) but that shouldn't matter. One difference I see is the line bolded in your output:
> 
> ```
> PLAYBOOK: meraki.yml *************************************************************************************************************************
> Positional arguments: meraki.yml
> verbosity: 4
> remote_user: ansible
> connection: smart
> timeout: 30
> **become: True**
> become_method: sudo
> tags: ('all',)
> inventory: ('/home/hawara/*work*/infra-ansible/inventories',)
> forks: 100
> 1 plays in meraki.yml
> ```
> 
> My output doesn't have that line. If it's doing privilege escalation, that may be dropping the environment variable. Is there something in your system or `ansible.cfg` which is setting `become`?

AHA!!!!!!!! That's it! Thank you for your help. Maybe, it's worth noting in a readme file, even though it should be obvious :man_facepalming:  

![image](https://user-images.githubusercontent.com/11381295/132933426-77777b9f-0e53-4027-94ef-07ccb68985c9.png)
