### ISSUE TITLE
Getting error on Cisco.meraki module

### ISSUE THREAD

**Issue by vinoymohan** [CiscoDevNet/ansible-meraki#255]
I tried to install the cisco meraki module on ansible and it says the module is already existing. But i am not able to query the module list for cisco.meraki. While i query, i get an error that cisco.meraki is not found .Is there a better way to install the module in ansible? 

root@abc:/etc/ansible# ansible-galaxy collection install cisco.meraki
Process install dependency map
Starting collection install process
Skipping 'cisco.meraki' as it is already installed
root@abc:/etc/ansible# ansible-doc -t inventory cisco.meraki
[WARNING]: inventory cisco.meraki not found in: /root/.ansible/plugins/inventory:/usr/share/ansible/plugins/inventory:/usr/lib/python2.7/dist-packages/ansible/plugins/inventory

**Comment by kbreit** [comment]
Very interesting. I'm going to look into this and will report back.

**Comment by kbreit** [comment]
As referenced in this issue I submitted this to the Ansible team for guidance. Let's keep this open until resolved though.

**Comment by kbreit** [comment]
Someone responded and brought up a good point. You seem to be looking up an inventory module. `cisco.meraki` doesn't have one. Please try something like `ansible-doc cisco.meraki.meraki_organization`. Does this work?

**Comment by vinoymohan** [comment]
Thanks Kevin for your support. When i upgrade the Ansible version to 2.11, the Meraki module worked. Thanks a lot for your time

**Comment by kbreit** [comment]
Thank you for the report and using the modules! Please let me know if there are any other ways I can help.
