### ISSUE TITLE
meraki_mx_l7_firewall doesn't accept its own rules

### ISSUE THREAD

**Issue by peetvandesande** [CiscoDevNet/ansible-meraki#287]
The meraki_mx_l7_firewall function gives an error when feeding it back a set of rules already configured:

```
TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "response.data": {
        "rules": [
            {
                "application_category": {
                    "id": "meraki:layer7/category/27",
                    "name": "Advertising"
                },
                "policy": "deny",
                "type": "applicationCategory"
            },
            {
                "host": "foo.bar",
                "policy": "deny",
                "type": "host"
            }
        ]
    }
}

TASK [Set rules] **************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (meraki_mx_l7_firewall) module: application_category found in rules. Supported parameters include: application, countries, host, ip_range, policy, port, type"}
```

This is my playbook:

```
- name: Test meraki playbook
  connection: local
  hosts: localhost
  vars:
    auth_key: key_secret
    org_id: '1234567'
    net_id: L_abc123
    front_rules: []
    back_rules: []

  tasks:
    - name: Get rules
      meraki_mx_l7_firewall:
        auth_key: '{{ auth_key }}'
        org_id: '{{ org_id }}'
        net_id: '{{ net_id }}'
        state: query
      delegate_to: localhost
      register: response
    - set_fact:
          original_ruleset: '{{ response.data.rules }}'
    - debug:
        var: response.data

    - name: Set rules
      meraki_mx_l7_firewall:
        auth_key: '{{ auth_key }}'
        org_id: '{{ org_id }}'
        net_id: '{{ net_id }}'
        state: present
        rules: '{{ response.data.rules }}'
      delegate_to: localhost
```

I'm working on Debian 11 and have version 2.6.9 of the cisco.meraki collection.

Any help is greatly appreciated!

**Comment by kbreit** [comment]
I wasn't notified of this issue so I apologize about the delay in acknowledging it. Hopefully this weekend I'll have a little time to look into this and respond. Thank you for submitting this.

**Comment by peetvandesande** [comment]
Thanks for looking into this, Keith. The problem seems to be with the application category. When I push just the host policy it's all fine.
I tried:
`{
  "application": "Advertising",
  "policy": "deny",
  "type": "applicationCategory"
}`
but that didn't help either. It gave me the below error:
`FAILED! => {"changed": false, "msg": "Failure when processing no_log parameters. Module invocation will be hidden. dictionary requested, could not parse JSON or key=value"}`

**Comment by kbreit** [comment]
Looking at the code, I'm inconsistent in what I'm showing. Do something like this. You should be able to pass in either the `id` as shown below or `name` with the application category name. Let me know if that works.
```
      - type: application_category
        application:
          id: meraki:layer7/category/24
```

**Comment by kbreit** [comment]
I believe so, yes. Most of my stuff uses snake case instead of camel case. I'm going to close this but if you think the documentation can be improved let me know.
