### ISSUE TITLE
meraki_mr_ssid -  splashGuestSponsorDomains param required when splash page is 'Sponsored guest'

### ISSUE THREAD

**Issue by KyleFryer-Sage** [CiscoDevNet/ansible-meraki#290]
I get the following error when trying to provision a 'Sponsored guest' splash page within an SSID.

Input:
```
"splash_page": "Sponsored guest",
"state": "present",
```
Results in:
``` 
"msg": "HTTP error 400 - <API URL> - splashGuestSponsorDomains param required when splash page is 'Sponsored guest'.",
    "response": "OK (unknown bytes)",
    "status": 400
```

I also get the following error when attempting the same via the Meraki Dashboard:
```
There were errors in saving this configuration:
     One or more errors occurred. No changes have been saved.
     Sponsor email domains are required.
```

There does not seem to be a parameter in the meraki_mr_ssid module for this; may just need to be added - this parameter is also present in the Meraki dashboard API module within the 'updateNetworkWirelessSsid' function of the Wireless class - https://github.com/meraki/dashboard-api-python/blob/6e68466ae79f0c1296f4836af22449e164d4c8c0/meraki/api/wireless.py#L1181

Thanks!

**Comment by kbreit** [comment]
Thanks again for your bug report. In this case it appears I never implemented the splash settings endpoint at https://developer.cisco.com/meraki/api-v1/#!update-network-wireless-ssid-splash-settings. This is probably new as of v1 and I didn't catch it when I did the migration. With that said, I will implement the functionality in the `meraki_mr_ssid` module.

**Comment by KyleFryer-Sage** [comment]
I think this particular parameter will have to be part of the `meraki_mr_ssid` module, as the `splashGuestSponsorDomains` parameter seems to be only required if the splash page `Sponsored Guest` is defined in the SSID module, so there is a dependence; and I find the same thing on the Dashboard (the parameter only becomes 'active' when `Sponsored Guest` is selected, on the same page)

![image](https://user-images.githubusercontent.com/82160360/157866166-fa519a58-f8c3-4943-bc71-d8ebe3c69c29.png)


But, yes, it would also be a good time to implement a separate module to update the splash page settings, that would be useful as I thought I would have to do that manually!

**Comment by kbreit** [comment]
Are you proposing I put the bare minimum values in the SSID module and then have a separate one for everything else?

**Comment by KyleFryer-Sage** [comment]
I'm proposing the parameters present in the function `def updateNetworkWirelessSsid` (https://github.com/meraki/dashboard-api-python/blob/6e68466ae79f0c1296f4836af22449e164d4c8c0/meraki/api/wireless.py#L1181) and also present via the API (https://developer.cisco.com/meraki/api-v1/#!update-network-wireless-ssid) are added to `meraki_mr_ssid`.

For example, this function accepts the following, and the Splash Page is also available in the SSID module:
```
- splashPage (string): The type of splash page for the SSID ('None', 'Click-through splash page', 'Billing', 'Password-protected with Meraki RADIUS', 'Password-protected with custom RADIUS', 'Password-protected with Active Directory', 'Password-protected with LDAP', 'SMS authentication', 'Systems Manager Sentry', 'Facebook Wi-Fi', 'Google OAuth', 'Sponsored guest', 'Cisco ISE' or 'Google Apps domain'). This attribute is not supported for template children.

- splashGuestSponsorDomains (array): Array of valid sponsor email domains for sponsored guest splash type.
```

And also just noticed the function supports `lanIsolationEnabled`, which is also not currently supported by `meraki_mr_ssid`:
```
- lanIsolationEnabled (boolean): Boolean indicating whether Layer 2 LAN isolation should be enabled or disabled. Only configurable when ipAssignmentMode is 'Bridge mode'.
```

And then a separate module would be fine using updating the splash page settings, as this is a physically separate page within the Dashboard, and has it's own API endpoint as you mentioned (https://developer.cisco.com/meraki/api-v1/#!update-network-wireless-ssid-splash-settings).

**Comment by kbreit** [comment]
@KyleFryer-Sage - I created PR #291. Please test and let me know if this resolves this issue. I'll create a new module hopefully in the near future.
