### ISSUE TITLE
meraki_switchport support for flex stacking

### ISSUE THREAD

**Issue by vladsker** [CiscoDevNet/ansible-meraki#327]
Hello, Kevin, everyone,

I've found that Meraki switchport module is missing support for the Flex stack port setting. In a nutshell, this feature allows a regular port to be used as a stacking port. 

More details are: 
Meraki documentation: https://documentation.meraki.com/MS/Stacking/Switch_Stacks;
Meraki API documentation: https://developer.cisco.com/meraki/api-latest/#!update-device-switch-port.

It looks like the fix is pretty straightforward, and I've developed a simple patch. But I can't create a pull request since I have no rights (or doing something wrong). So can you look at this, please? Maybe, you can allow me to pull requests (and push branches)? Or perhaps, this feature is already somewhere on a roadmap? 

Thanks and regards,
Vlad

**Comment by kbreit** [comment]
Thanks for pointing this out. It's actually missing a few items I intend to add. I've got some plans this evening but should be able to implement it over the next few days and create a new version next week.

**Comment by vladsker** [comment]
Thanks a lot for looking into this, Kevin. I will be waiting.
