### ISSUE TITLE
CopyFromId in meraki_network module

### ISSUE THREAD

**Issue by charrrr93** [CiscoDevNet/ansible-meraki#335]
Hi,

Just wanted to see if there is something in the roadmap to add the CopyFromId field into the meraki_network module? I find this super convenient for a new rollout of devices so that all the basic network settings are just copied from my manually configured site rather than going back and updating them via the API. Things like the local status page, snmp, syslog, analytics etc.

Thanks,
Charlotte

**Comment by kbreit** [comment]
Thank you for reporting this. I wasn't aware it was an option. Having said that it's sensible to include so I'll look to add it.

**Comment by charrrr93** [comment]
Awesome, thank you so much. And thanks for the quick reply!

**Comment by charrrr93** [comment]
That was such a quick turn around and I just checked and it works perfectly. Thanks so much!
