### ISSUE TITLE
Wrong shebang in scripts/sublime-build/build.py.generic

### ISSUE THREAD

**Issue by johanneskastl** [CiscoDevNet/ansible-meraki#341]
https://github.com/CiscoDevNet/ansible-meraki/blob/f6c2b74c9a74103f7e08e2e39728b3578a3e5668/scripts/sublime-build/build.py.generic#L1

I guess the shebang should not be `/Users/kbreit/Documents/Programming/ansible_collections/cisco/meraki/venv/bin/python`?

**Comment by kbreit** [comment]
@johanneskastl I did a release of Ansible to 2.10.1 and it should be changed. Which version are you looking at?

**Comment by johanneskastl** [comment]
Sorry, I looked at the wrong branch apparently. Seems to be fixed in master:
https://github.com/CiscoDevNet/ansible-meraki/blob/master/scripts/sublime-build/build.py.generic#L1
