### ISSUE TITLE
meraki_mx_site_to_site_vpn check mode is posting changes

### ISSUE THREAD

**Issue by DerrickTJ** [CiscoDevNet/ansible-meraki#410]
meraki_mx_site_to_site_vpn "--check" is actually pushing changes instead of checking that it should make the change and not post them.

ansible [core 2.14.1]
python version = 3.11.1

**Comment by DerrickTJ** [comment]
Just verified the module, it is marked that is supports check mode `supports_check_mode=True` but doesn't have any checks in place to verify it is in check mode. Missing: `if meraki.module.check_mode is True:`

**Comment by y0rune** [comment]
Hello!
I see that issue in the code. Can you provide the example playbook for test it? 

Thank you!
Marcin

**Comment by DerrickTJ** [comment]
The example in the documentation should work just fine. It's nothing specific to how I write it.

**Comment by y0rune** [comment]
To be honest I think like you said we have to add the missing if statement. You are absolutely right. As far I see that statement is appeared in the another modules. What do you think @kbreit?

Thank you for posting that issue @DerrickTJ ;)

**Comment by DerrickTJ** [comment]
I would have added it myself but for some odd reason we cannot edit the code and submit PRs for them to get merged here in this org.

**Comment by kbreit** [comment]
Thanks for submitting the bug report. We can either disable check mode or look into adding support for it. The former is easier than the latter but neither should be awful. Do you have a use case for check mode in your environment?

**Comment by kbreit** [comment]
Makes sense. Let me look at issuing a fix for this. Are you able to run test code to verify my changes are complete?

**Comment by DerrickTJ** [comment]
Yeah, I should be able to.
