### ISSUE TITLE
Trying to get Kevin's attention

### ISSUE THREAD

**Issue by obrigg** [CiscoDevNet/ansible-meraki#453]
Hello Kevin,
After trying mail, Webex, and LinkedIn - I thought I'll try to give an Ansible issue a shot.
My name is Oren, and I'm a product manager on the Meraki API and ecosystem PM team.

I'd love to get in touch with you.
Mail: obrigg at cisco dot com
Webex: same mail.
LinkedIn, Twitter.. whatever works for you.

Thanks,
Oren.

**Comment by kbreit** [comment]
I messaged on LinkedIn. Closing the issue.
