### ISSUE TITLE
Future of the ansible-meraki on CiscoDevNet

### ISSUE THREAD

**Issue by y0rune** [CiscoDevNet/ansible-meraki#464]
Hello!
I would like to ask what will happend with ansible-meraki and with all your work @kbreit ?
As far I as Cisco adopt code from here into a non-ciscodev repo :C

--
Marcin

**Comment by kbreit** [comment]
@y0rune Good question. I just (a minute or two ago) announced a deprecation date of the collection on May 1. While I've enjoyed maintaining this collection, Cisco is best positioned to maintain it. Furthermore, they're automating the module creation so they get a ton of modules that I don't have. I do appreciate all your help and over the next few months am happy to work with you on enhancements until May 1.
