### ISSUE TITLE
New module - meraki_mx_site_to_site_vpn

### ISSUE THREAD

**Issue by kbreit** [CiscoDevNet/ansible-meraki#59]
Meraki had support for configuring and querying site-to-site VPN information. A new module should be created to support this.

https://developer.cisco.com/meraki/api/#/rest/api-endpoints/networks/get-network-site-to-site-vpn

This issue is merged from ansible/ansible from issue request https://github.com/ansible/ansible/issues/55997.

**Comment by kbreit** [comment]
@pokepoke81 - This module will be almost identical to `meraki_mx_l3_firewall`. With that in mind, I'm waiting to create `meraki_mx_site_to_site_vpn` until #62 is merged so I can take that bugfix and have it work in this module.

**Comment by kbreit** [comment]
@pokepoke81 I don't know if you'll be notified on the new PR, but please check out #68. Test and let me know if it works.

**Comment by kbreit** [comment]
Also, there isn’t an endpoint to configure site to site VPNs as far as I can tell. The best I can do is firewall rules for them.

**Comment by pokepoke81** [comment]
I'm trying to piece some things together. It seems that Site to Site VPN settings are defined in the Network: [](https://developer.cisco.com/meraki/api/#/python/api-endpoints/networks/update-network-site-to-site-vpn)
You're right that there is a different endpoint for the VPN firewall.

So, do you have a separate module to add VLANs to the Site-to-Site VPN like the API? Or do you allow adding/editing them with the `meraki_vlan` module (which is how the dashboard works)?

This will also apply to static routes defined on the MX. [](https://community.meraki.com/t5/Developers-APIs/VPN-Static-Routes-through-API/m-p/50002)

**Comment by pokepoke81** [comment]
Also, I don't have a way to test your PR. I only have one organization and it's production. I'm testing the MS and MX stuff against spare hardware in the organization. I don't think that will work for me since VPN settings are across the organization, not the network.

**Comment by kbreit** [comment]
You may be able to create a new organization without licensing to test the module.

**Comment by pokepoke81** [comment]
@kbreit I'm on a deadline this week, so haven't had a chance to get to this. Hopefully I can find a way to test it next week.

**Comment by kbreit** [comment]
No problem. Let me know when you're able to test it.
