### ISSUE TITLE
Questions on support

### ISSUE THREAD

**Issue by pokepoke81** [CiscoDevNet/ansible-meraki#60]
Disclaimer: I'm relatively new to Ansible

I see the galaxy.yml, so does this replace the modules built into Ansible and therefore I need to install the galaxy modules?

There a place to ask questions on using the modules? I'm seeing some strange behavior, but don't know that it's an issue or just bad configuration on my part.

**Comment by kbreit** [comment]
@pokepoke81 This will eventually replace the modules built into Ansible. As of 2.10 the modules will be removed from Ansible and you’ll have to use these. I’m focusing my development on this repository and not the mainstream Ansible ones.

When you see odd behavior, please submit an issue here, just like this one. Please include the output and a sanitized, simplified, playbook which causes the problem.

**Comment by pokepoke81** [comment]
Thanks Kevin. I'll switch over to the galaxy version and start posting issues I find.

**Comment by kbreit** [comment]
I'm closing this issue. But as I said, please open new issues for features or bugs.
