### ISSUE TITLE
Enable DHCP and DHCP options with Meraki_vlan

### ISSUE THREAD

**Issue by pokepoke81** [CiscoDevNet/ansible-meraki#63]
Looking through the options for meraki_vlan, I do not see a way to enable DHCP on a vlan and configure it's options. Also, does meraki_vlan work against layer 3 meraki switches, or only the MX?

**Comment by kbreit** [comment]
I would need to test `meraki_vlan` working against a layer 3 switch but I suspect it would only work with an MX appliance. Are you trying to setup an SVI on a layer 3 switch?

`meraki_vlan` has the ability to configure DHCP settings. I can see how it's not very obvious. It supports reserved IP ranges, fixed IP assignments, etc.

**Comment by pokepoke81** [comment]
This all has my attention because I'm working on putting my existing infrastructure into code. I have 10 interfaces on my MS350 switch stack I'm trying to replicate. Some have DHCP settings, others do not. The MS350 also can do OSPF on the interfaces, which I have configured.

On the MX, I see the reserved and fixed IP's in `meraki_vlan` but I don't see how you'd turn the DHCP server on or off from the options shown in the documentation.

**Comment by kbreit** [comment]
I looked into this and indeed, the `meraki_vlan` module lacks a full suite of DHCP options. I need to decide whether to create a new module called `meraki_dhcp` or if I should fold it into `meraki_vlan`. I’m leaning toward the latter. OSPF isn’t configurable via the API yet (https://dashboard.meraki.com/api_docs) as far as I can tell. If I’m missing it, please direct me to the endpoint and I’ll look into it.

I haven’t tested whether `meraki_vlan` works on a MS device yet.

**Comment by pokepoke81** [comment]
It makes sense to me that the DHCP options would be with the `meraki_vlan` since it's a one-to-one relationship. I tested creating new VLANs on a test device and it enabled the DHCP server by default.

I don't see OSPF settings in the API either. I don't see any way to set an SVI on a switch from the API. That's going to give me trouble.

**Comment by kbreit** [comment]
Thanks for the feedback. I'll add more DHCP options to `meraki_vlan` in the coming week or two.
