### ISSUE TITLE
Case of 'Any' in causes changes

### ISSUE THREAD

**Issue by pokepoke81** [CiscoDevNet/ansible-meraki#80]
Not sure if this is fixable, but having the improper case for 'Any' in CIDR and Port references on the firewall will always report a change. CIDR and Port need to be 'Any', but Meraki will accept 'any' and capitalize it for you. This causes the module to report 'changed' on every execution though, because it's changing the case.

Protocol must be 'any' and Meraki will error if you provide 'Any'. Could the module fix the case per Meraki's expectations before submitting to the API?

**Comment by kbreit** [comment]
@pokepoke81 I'm not surprised this came up but I can fix it. I have thought about normalizing capitalization on any to get around this.

**Comment by kbreit** [comment]
@pokepoke81 I have a fix in the `meraki_mx_l3_firewall`module. Are you able to test using this module? What module are you having problems with?
