### ISSUE TITLE
Missing doc_fragments/meraki.py

### ISSUE THREAD

**Issue by gundalow** [CiscoDevNet/ansible-meraki#96]
Hi,
Looks like `doc_fragments/meraki.py` is missing from this repo.
You can copy the file from the `pre-ansible-base` branch.

https://github.com/ansible/ansible/tree/pre-ansible-base/lib/ansible/plugins/doc_fragments

**Comment by kbreit** [comment]
@gundalow Github doesn't always notify me of issues being created so I'm just seeing this. Please see https://github.com/CiscoDevNet/ansible-meraki/pull/99 and let me know if this fixes it.
