### ISSUE TITLE
meraki_admin - KeyError: 'network' 

### ISSUE THREAD

**Issue by sstone173** [CiscoDevNet/ansible-meraki#97]
When trying to create an admin with network(s) assigned during creation, I'm receiving the following error:

Traceback (most recent call last):
  File "/home/steve/.ansible/tmp/ansible-tmp-1592414226.5026495-265972714452428/AnsiballZ_meraki_admin.py", line 102, in <module>
    _ansiballz_main()
  File "/home/steve/.ansible/tmp/ansible-tmp-1592414226.5026495-265972714452428/AnsiballZ_meraki_admin.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/steve/.ansible/tmp/ansible-tmp-1592414226.5026495-265972714452428/AnsiballZ_meraki_admin.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.meraki.meraki_admin', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py", line 498, in <module>
  File "/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py", line 470, in main
  File "/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py", line 336, in create_admin
  File "/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py", line 316, in network_factory
KeyError: 'network'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/steve/.ansible/tmp/ansible-tmp-1592414226.5026495-265972714452428/AnsiballZ_meraki_admin.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/steve/.ansible/tmp/ansible-tmp-1592414226.5026495-265972714452428/AnsiballZ_meraki_admin.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/steve/.ansible/tmp/ansible-tmp-1592414226.5026495-265972714452428/AnsiballZ_meraki_admin.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.meraki.meraki_admin', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py\", line 498, in <module>\n  File \"/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py\", line 470, in main\n  File \"/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py\", line 336, in create_admin\n  File \"/tmp/ansible_meraki_admin_payload_2hzpculp/ansible_meraki_admin_payload.zip/ansible/modules/network/meraki/meraki_admin.py\", line 316, in network_factory\nKeyError: 'network'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Playbook:

---
- name: Meraki Playbook - Create User
  connection: local
  hosts: localhost

  tasks:

    - name: Create a new administrator with full access to a network
      meraki_admin:
        auth_key: 
        org_id: 
        state: present
        name: Test User
        org_access: none
        email: testuser@email.com
        networks:
            - id: N_12345XXXXXXXXXXX
              access: full

**Comment by kbreit** [comment]
I didn't see this one come in last night. Give me a little time to test and report back. Thank you for the report!

**Comment by kbreit** [comment]
@sstone173 I was able to verify this bug and fix it. Please try the code in https://github.com/CiscoDevNet/ansible-meraki/pull/100. Let me know if you're not familiar with how to pull these changes.

**Comment by sstone173** [comment]
@kbreit I'm pretty new to this, so I'm not familiar with how to pull these changes into my local environment (Ubuntu 20.04 in WSL2), any help would be greatly appreciated :)

**Comment by kbreit** [comment]
@sstone173 I can't speak to WSL2 but my guess is in your home directory in Linux you'll find a .ansible directory. I have `~/.ansible/collections/ansible_collections/cisco/meraki`. If you have that, continue drilling down to `plugins/modules/` or something like that. In there should be a bunch of Python files which are the actual modules. Copy `meraki_admin.py` off into a backup and then download https://raw.githubusercontent.com/CiscoDevNet/ansible-meraki/e90798e616b0935133443511eb67eb7823b189fb/plugins/modules/meraki_admin.py over it. That will be the new version to test with. Let me know how this process goes.

**Comment by sstone173** [comment]
@kbreit Was able to get the file updated and confirm that it is working now, thanks for all the help!

**Comment by kbreit** [comment]
Glad to hear it works. I’ll have a new release this weekend with the fix.
